### ISSUE TITLE
Automatically release after successful build in Travis

### ISSUE THREAD

**Issue by rpkamp** [ibuildingsnl/qa-tools#83]
It is quite easy to make a GitHub release after a Travis was successful by adding something like the following to `.travis.yml`:

```
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - "qa-tools.phar"
    - "qa-tools.phar.pubkey"
  skip_cleanup: true
  on:
    branch: master
    tags: true
```

Assuming the Travis build created artifacts `qa-tools.phar` and `qa-tools.phar.pubkey`.

See https://docs.travis-ci.com/user/deployment/releases/

This requires a github token to be set in the Travis environment variables with key `GITHUB_TOKEN`. This key must be created by a GitHub account that has write access to the repository and must have the `repo` permission enabled. Travis will not output this variable during build and for a PR from a fork it won't even load the variable at all, so people can't `echo` it.

Of course this required the private key to sign the phar file as well, but that can be encrypted and put in the repository as well in a way that Travis can use it but nobody else can. See https://docs.travis-ci.com/user/encrypting-files/

Combine this with [RMT][rmt] for version tagging and changelog management and all the whole release process is fully automated :smiley: 

[rmt]: https://github.com/liip/RMT
