### ISSUE TITLE
Configure Travis when the developer requests that Travis be integrated into their project

### ISSUE THREAD

**Issue by rjkip** [ibuildingsnl/qa-tools#88]
- [ ] Revert changes from #111
 - [ ] Figure out what is common for Drupal projects

```yml
# .travis.yml
sudo: false
language: php
php:
  - 5.6
  - 7.0
  - 7.1

env:
  global:
    - SYMFONY_ENV=test # For Symfony projects

cache:
  directories:
    - ~/.composer/cache/files/

before_script:
  - phpenv config-add .travis.php.ini
  - composer self-update
  - composer install --prefer-dist

script:
  - ant

branches:
  only:
    - master
    - develop
```

```ini
# .travis.php.ini
date.timezone = "<Current PHP runtime's timezone>"
```
